// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDsxk6y4pVWi8au0FQ_Brtn4qyU7mGvE',
    appId: '1:420471406105:web:b4af34565fd8cb9932f488',
    messagingSenderId: '420471406105',
    projectId: 'hackaton-da764',
    authDomain: 'hackaton-da764.firebaseapp.com',
    storageBucket: 'hackaton-da764.appspot.com',
    measurementId: 'G-V7ZE60W157',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDKxycKg94koYdv5HSl4gxZF9CcS7Aws',
    appId: '1:420471406105:android:68a2adb7babaf6ff32f488',
    messagingSenderId: '420471406105',
    projectId: 'hackaton-da764',
    storageBucket: 'hackaton-da764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusrgYocN958ghsF9LU9HD__mOBaHChA8',
    appId: '1:420471406105:ios:3434b37bad7579b632f488',
    messagingSenderId: '420471406105',
    projectId: 'hackaton-da764',
    storageBucket: 'hackaton-da764.appspot.com',
    iosClientId: '420471406105-h81hssrdpennt0kjajg3f6eb75j4092a.apps.googleusercontent.com',
    iosBundleId: 'fr.istic.hacki.festival',
  );
}
